### ISSUE TITLE
TypeError: LocationItem is not JSON serializable

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#2]
```
Traceback (most recent call last):
  File ".../env/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File ".../env/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 64, in process_spider_output
    result = method(response=response, result=result, spider=spider)
  File ".../env/lib/python3.7/site-packages/scrapy_autounit/middleware.py", line 69, in process_spider_output
    self.add_sample(callback_counter + 1, fixtures_dir, data)
  File ".../env/lib/python3.7/site-packages/scrapy_autounit/middleware.py", line 43, in add_sample
    add_file(data, path)
  File ".../env/lib/python3.7/site-packages/scrapy_autounit/utils.py", line 58, in add_file
    json.dump(data, outfile, sort_keys=True, indent=2)
  File "/usr/lib64/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib64/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LocationItem is not JSON serializable
```

AFAICT the items is pretty normal, just a bunch of fields.  It's derived from `scrapy.Item`

**Comment by fcanobrash** [comment]
Solved in #3, closing the issue.
