### ISSUE TITLE
Spider attributes

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#23]
So this goes along with the mention of untracked dependencies (#14), but I have a spider that has a `page_number` attribute that's incremented after every `yield self.next_page()` call.  It's initialized to 0, so when recording a callback might request page 10, but during playback the same code now requests page 0.

There's a solution to this, which is to pass `page_number` to the callback via `meta`, and since there's no branching (the increment always happens in one callback which is requested by the callback that did the previous increment) this works and isn't too difficult.

But I wonder if autounit could track spider attributes?

**Comment by andrewbaxter** [comment]
Here's an example spider:
```python
import scrapy


class HijSpider(scrapy.Spider):
    name = 'hij'

    def __init__(self, *pargs, **kwargs):
        super().__init__(*pargs, **kwargs)
        self.i = 0

    def start_requests(self):
        yield self.next_req()

    def next_req(self):
        self.i += 1
        return scrapy.Request('data:text/plain,hi', dont_filter=True)

    def parse(self, response):
        print('i {}'.format(self.i))
        if self.i < 3:
            yield self.next_req()
```
Recorded, then during test playback:
```
$ python -m unittest discover -v
test__hij__parse__fixture1 (autounit.tests.hij.parse.test_fixture1.AutoUnit) ... /.../env/lib/python3.6/site-packages/scrapy/utils/conf.py:97: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  cfg = SafeConfigParser()
i 0
ok
test__hij__parse__fixture2 (autounit.tests.hij.parse.test_fixture2.AutoUnit) ... i 0
ok
test__hij__parse__fixture3 (autounit.tests.hij.parse.test_fixture3.AutoUnit) ... i 0
FAIL

======================================================================
FAIL: test__hij__parse__fixture3 (autounit.tests.hij.parse.test_fixture3.AutoUnit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/.../xyz/autounit/tests/hij/parse/test_fixture3.py", line 13, in test__hij__parse__fixture3
    test(self)
  File "/.../env/lib/python3.6/site-packages/scrapy_autounit/utils.py", line 303, in test
    "The fixture's data length doesn't match with "
AssertionError: The fixture's data length doesn't match with the current callback's output length.

----------------------------------------------------------------------
Ran 3 tests in 0.072s

FAILED (failures=1)
```
In the output, i=0 is printed each time.

**Comment by mabelvj** [comment]
Thanks for testing it out @andrewbaxter. I added this spider as a test and fixed the issues causing the attribute not being updated. You can check it out know.
